In [2]:
import torch

In [ ]:
x = torch.ones(2, requires_grad=True)
print(x, x.shape, x.size())
z = x + 2
print(z, z.shape, z.size())
z.backward(torch.ones_like(z))
# z.backward() # Error: grad can be implicitly created only for scalar outputs
print(x.grad)

tensor([1., 1.], requires_grad=True) torch.Size([2]) torch.Size([2])
tensor([3., 3.], grad_fn=<AddBackward0>) torch.Size([2]) torch.Size([2])
tensor([1., 1.])


In [ ]:
# 不清除梯度张量，只把梯度值归零
x.grad.zero_()
# x.grad = None  # 清除梯度张量
m = x + 2
m.sum().backward()
print(x.grad)

tensor([1., 1.])


In [9]:
x = torch.tensor([2., 1.], requires_grad=True)
y = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)

z = torch.mm(x.view(1, 2), y)
print(f"z:{z}")
z.backward(torch.Tensor([[1., 0]]), retain_graph=True)
print(f"x.grad: {x.grad}")
print(f"y.grad: {y.grad}")

z:tensor([[5., 8.]], grad_fn=<MmBackward0>)
x.grad: tensor([1., 3.])
y.grad: tensor([[2., 0.],
        [1., 0.]])
